### ISSUE TITLE
movecost not working after last update

### ISSUE THREAD

**Issue by CretaCreta** [enzococca/movecost#1]
Hi and thank you very much for the your efforts. I am an archaeologst and wrok a lot with movecost in QGIS. After last update it cannot calucalte anything and I get the following message: 

Error in as(x, "dgTMatrix") :
no method or default for coercing "ddiMatrix" to "dgTMatrix"
Calls: movecost ... geoCorrection -> .local -> adjacencyFromTransition -> as
Execution halted
Execution completed in 5.25 seconds
Results:
{'Output_Accum_Cost_Surface': 'C:/Users/anton/AppData/Local/Temp/processing_QOLkCx/3b3fa56dae9e469291becbf88e3e5d05/Output_Accum_Cost_Surface.tif',
'Output_Isoline': 'C:/Users/anton/AppData/Local/Temp/processing_QOLkCx/55ec9655972748499b6837759285ca8d/Output_Isoline.gpkg',
'Output_LCP': 'C:/Users/anton/AppData/Local/Temp/processing_QOLkCx/3c3bf9d4d5fa4b08b5649d2152f783b4/Output_LCP.gpkg',
'Output_LCP_Back': 'C:/Users/anton/AppData/Local/Temp/processing_QOLkCx/d07f4f0e5280450995463a5c0412965f/Output_LCP_Back.gpkg',
'Output_W_Cost': 'C:/Users/anton/AppData/Local/Temp/processing_QOLkCx/ae7af1c4bf8c40fb8607b00d57825630/Output_W_Cost.gpkg',
'RPLOTS': 'C:/Users/anton/AppData/Local/Temp/processing_QOLkCx/e6232c2347cb4bcd9aea2bfd68c9e519/RPLOTS.html'}

I installed the previous version but I get the same result. Any ideas?

Cheers,

B.

**Comment by enzococca** [comment]
Hi,

Check if in you R it's installed the last version of movecost (release 2.1
i think)

And try again

Il sab 6 gen 2024, 18:51 CretaCreta ***@***.***> ha scritto:

**Comment by CretaCreta** [comment]
Thank you very much. I'll have look now!

B.
